### ISSUE TITLE
mechanism to build outside a git repository

### ISSUE THREAD

**Issue by droundy** [fusion-engineering/rust-git-version#10]
It would be nice to have a macro that does something other than crash when run outside a git repository, since cargo builds outside git repositories (see droundy/fac#24).  I could see this either working through a separate macro (`git_describe_or_cargo_version!`?), or via a special flag to `git_describe`.  Any preference for which mechanism you'd like for a pull request, or what you'd like to call the non-crashing macro?

**Comment by droundy** [comment]
We've now had for a couple of weeks two separate implementations that will accomplish this.  Any chance we can get one merged so I can make my code work with `cargo install`?

**Comment by m-ou-se** [comment]
Hey sorry for the delay. Just came back from holiday. Merged #12 to support this use case.

(I still think https://github.com/fusion-engineering/rust-git-version/pull/12#issuecomment-559149747 would be nice, but have no time to implement it. We can always add that later.)
