### ISSUE TITLE
Recoverable Git Error

### ISSUE THREAD

**Issue by bodo-hugo-barwich** [fusion-engineering/rust-git-version#16]
I'm working on a solution to recover from an Error in the `git_version!()` macro call
as documented at:
[Build fails without Git](https://github.com/ChainSafe/forest/issues/1384)
I noticed that many error cases are captured by the macro which I think is a nice work.
Now, I'm implementing a fallback solution for build environments without _Git_.
Right now, when _Git_ is not installed the macro panicks:
```
error: No such file or directory (os error 2)
  --> forest/build.rs:65:19
   |
65 |     let git_cmd = git_version!()?;
   |                   ^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `proc_macro_call` (in Nightly builds, run with -Z macro-backtrace for more info)
```
extending this message by rebuilding the `Command` call it results in:
```
     Running `/home/rust-build/project/target/debug/build/forest-3e9549a222c5efe9/build-script-build`
error: failed to run custom build command for `forest v0.2.2 (/home/rust-build/project/forest)`

Caused by:
  process didn't exit successfully: `/home/rust-build/project/target/debug/build/forest-3e9549a222c5efe9/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "Git Commmand: command failed with Error: 'Os { code: 2, kind: NotFound, message: \"No such file or directory\" }'" }', forest/build.rs:72:12
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which means that the `Command` produced an `std::io::Error` of kind `ErrorKind::NotFound` because _Git_ **is not installed**.
```
rust_builder@cc9582f0ba11:~/project$ which git |wc -l
0
rust_builder@e4a718bcf520:~/project$ git rev-parse --short HEAD 2>git_error.txt >git_log.txt ; echo "res: '$?'"
res: '127'
rust_builder@e4a718bcf520:~/project$ cat git_log.txt|wc -l
0
rust_builder@e4a718bcf520:~/project$ cat git_error.txt
bash: git: command not found
```
On the other side when _Git_ is installed but the `.git/` directory is missing the `Command` call finished but returns a `Exit Status` of `128` and prints an Error Message to `STDERR` as seen in:
```
$ git rev-parse --short HEAD 2>git_error.txt >git_log.txt ; echo "res: '$?'"
res: '128'
$ cat git_log.txt |wc -l
0
$ cat git_error.txt
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
I'm looking for a way to handle this in a uniform way to implement an alternative logic which does not rely on _Git_. 
Is there any function that could return a `Result<String>` struct ?

**Comment by DarrienG** [comment]
+2 for this. I would love to be able to provide officially released binaries that have git hash recorded in, but still allow users to build it on their own (probably with a `cargo install`)

**Comment by hoijui** [comment]
I think this PR is related: https://github.com/fusion-engineering/rust-git-version/pull/17

It seems to do half the job: Fall back to cargo if dir has no `.git`.

**Comment by bodo-hugo-barwich** [comment]
The implementation of this concept is blocked by a limitation as documented in the Official Rust Documentation:
https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macros
> As functions, they must either return syntax, panic, or loop endlessly.
So, an implementation returning an enumeration `syn::Result<TokenStream>` fails:
```
145 | / pub fn git_version(input: TokenStream) -> syn::Result<TokenStream> {
146 | |     let args = parse_macro_input!(input as Args);
147 | |
148 | |     let tokens = git_version_impl(args)?;
...   |
154 | |     Ok(TokenStream::from(tokens))
155 | | }
    | |_^ expected struct `proc_macro::TokenStream`, found enum `Result`
    |
    = note: expected fn pointer `fn(proc_macro::TokenStream) -> proc_macro::TokenStream`
                  found fn item `fn(proc_macro::TokenStream) -> Result<proc_macro::TokenStream, syn::Error> {git_version}`
```
Then the implementation as new function in `git-version-macro` as perhaps `try_git_version()` also fails:
```
error: `proc-macro` crate types currently cannot export any items other than functions tagged with `#[proc_macro]`, `#[proc_macro_derive]`, or `#[proc_macro_attribute]`
   --> git-version-macro/src/lib.rs:156:1
    |
156 | pub fn try_git_version(input: TokenStream) -> syn::Result<TokenStream> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
So, an implementation as `syn::Result<TokenStream>` is force to happen in a new crate.

**Comment by bodo-hugo-barwich** [comment]
For this new crate to be able to use the existing function `git_version::git_version_impl()` to simplify the implementation would require a mayor restructuring of the project because auxiliary functions used by `git_version::git_version()` are also subjected to this limitation.

**Comment by hoijui** [comment]
please see #22

**Comment by de-vri-es** [comment]
Hmm, the proc macro doesn't panic as it is. I've improved the error reporting a bit though, so it should be more clear what the exact problem is.

If you want to avoid the compile error, you can use `cargo_prefix/suffix` and/or the `fallback` argument :)

If this doesn't fit your needs, feel free to comment. I can re-open the issue.
