### ISSUE TITLE
Project abandonned -> Fork!

### ISSUE THREAD

**Issue by hoijui** [fusion-engineering/rust-git-version#22]
Hey everyone interested.
It seems obvious that this repo is not maintained anymore (last activity was in December 2021) , thus I suggest to fork it, maybe rename it in the fork, and adding a few of the people that made PRs here maintainers on the new repo, so we will not end up with a headless repo again so easily.
Then we should of course also release that new version; probably under a new name.

Looking shortly at the forks with changes here:
https://github.com/fusion-engineering/rust-git-version/network
I would have chosen [@darthdeus](https://github.com/darthdeus/git-version/tree/master) fork as the new base,
but maybe the current version from this repo would be more democratic and save.

I am happy with anyone doing this. I would also do the basic part of it myself, if no-one else steps up.

**Comment by baxterjo** [comment]
I would prefer a new fork. I understand why [@darthdeus](https://github.com/darthdeus/git-version/tree/master) made the fork they did. But I want to keep args.

**Comment by de-vri-es** [comment]
Hello! I understand the sentiment. But honestly, for the API, I think very little additions or changes are needed. This is basically just a simple wrapper around `git describe` and it is not intended to be more.

The upgrade to `syn` v2 was nice and is now released.

Something to make it work when run outside of git also makes sense, so a PR that creates a static `Result` or `Option` would be something I would certainly appreciate too.

**Comment by de-vri-es** [comment]
Anyway, thanks for the reminder that this crate needs some maintenance. Closing this issue since I'm looking at the repository now :)

**Comment by hoijui** [comment]
Thank you @de-vri-es for the care that day! :-)
